name: deploy

on:
  push:
    branches:
      - aws

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  GITHUB_SHA: ${{ github.sha }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with: '3.x'
      - name: Run Py Script
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --user awscli
          python3 -m pip install --user awsebcli
      - name: Run Deploy Script
      - run: sh ./scripts/deploy.sh
